config/routes.rb
Rails.application.routes.draw do
	resources :ships do
		resources :equips,only: [:create,:destroy]
	end
	resources :eq_data

	root 'ships#index'
end

app/models/eq_datum.rb
class EqDatum < ActiveRecord::Base
	def view_name_and_scores
		self.name+"( "+self.score.to_s+" => "+(self.score*self.rate).round(2).to_s+" )"
	end

end

app/models/equip.rb
class Equip < ActiveRecord::Base
  belongs_to :ship
  validates :name, :score, presence: true
end

app/models/ship.rb
class Ship < ActiveRecord::Base
	has_many :equips
	validates :name,
	presence: {message: "入力してください" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/eq_data_controller.rb
class EqDataController < ApplicationController
	before_action :set_eq_datum,only:[:show,:edit,:update,:destroy]
	def index
		@data=EqDatum.all
	end
	def new
		@eq_datum=EqDatum.new
	end

	def create
		@eq_datum=EqDatum.new(eq_datum_params)
		if @eq_datum.save
			redirect_to eq_data_path
		else
			render "new"
		end
	end
	def edit
	end

	def update
		
		@eq_datum.update(eq_datum_params)
		redirect_to eq_data_path
	end

	def destroy
		@eq_datum.destroy
		redirect_to eq_data_path
	end

	private
	def set_eq_datum
		@eq_datum=EqDatum.find(params[:id])
	end
	def eq_datum_params
		params.require(:eq_datum).permit(:name , :score, :rate)
	end
end

app/controllers/equips_controller.rb
class EquipsController < ApplicationController
	def create
		@ship=Ship.find(params[:ship_id])
		@eq_datum=EqDatum.find(equip_params[:eq_datum_id])
puts "**********************************"
puts equip_params[:eq_datum_id]
puts "**********************************"
		@equip=@ship.equips.new(name: @eq_datum.name, score: @eq_datum.score, rate: @eq_datum.rate)
		@equip.save
		redirect_to ship_path(@ship.id)
	end
	def destroy
		@equip=Equip.find(params[:id])
		@equip.destroy
		redirect_to ship_path(params[:ship_id])
	end

	private
	def equip_params
		params.require(:equip).permit(:eq_datum_id)
	end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
	before_action :set_ship,only:[:show,:edit,:update,:destroy]

	def index
		@ships=Ship.all
	end

	def show
		teisatuki_rate=[1.66,2.00,1.78]
		dentan_rate=[1.00,0.99]
		@teisatuki=[]
		@dentan=[]
		@other=[]
		EqDatum.all.each do |eq|
			case eq.rate
			when *teisatuki_rate then @teisatuki << eq
			when *dentan_rate then @dentan << eq
			else @other << eq
			end
		end
	end

	def new
		@ship=Ship.new
	end

	def create
	#	@ship=Ship.create(params[:ship])
		@ship=Ship.new(ship_params)
		if @ship.save
			redirect_to ships_path
		else
			render "new"
		end
	end
	def edit
	end
	def update
		@ship.update(ship_params)
		redirect_to ships_path
	end
	def destroy
		@ship.destroy
		redirect_to ships_path
	end
	
	private
	def ship_params
		params.require(:ship).permit(:name , :score)
	end
	def set_ship
		@ship=Ship.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eq_data_helper.rb
module EqDataHelper
end

app/helpers/equips_helper.rb
module EquipsHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/eq_data/_form.html.erb
<%= form_for @eq_datum do |f| %>
<p>
	<%= f.label :name %>
	<%= f.text_field :name %><br>
	<%= f.label :score %>
	<%= f.text_field :score %><br>
	<%= f.label :rate %>
	<%= f.text_field :rate %><br>
	<%if @eq_datum.errors.any? %>
		<%= @eq_datum.errors.messages[:name][0] %>
	<% end %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/eq_data/edit.html.erb
<h1>edit</h1>
<%= render 'form' %>

app/views/eq_data/index.html.erb
<h1>装備データ一覧</h1>
<table border=1>
	<tr>
		<th>装備名</th>
		<th>値</th>
		<th>倍率</th>
	</tr>
	<% @data.each do |datum| %>
		<tr>
			<td><%= datum.name %></td>
			<td><%= datum.score %></td>
			<td><%= datum.rate %></td>
			<td><%= link_to "Edit",edit_eq_datum_path(datum.id) %></td>
			<td><%= link_to "Delete",eq_datum_path(datum.id),method: :delete,data:{confirm:"よろしいですか？"} %>&emsp;</td>
		</tr>
	<% end %>
</table>
<%= link_to "create new",new_eq_datum_path %><p>

app/views/eq_data/new.html.erb
<h1>new</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sakuteki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= image_tag "logo.png" %>
<%= yield %>
<%= link_to "HOME",ships_path %>
</body>
</html>

app/views/ships/_form.html.erb
<%= form_for @ship do |f| %>
<p>
	<%= f.label :name %>
	<%= f.text_field :name %><br>
	<%= f.label :score %>
	<%= f.text_field :score %><br>
	<%if @ship.errors.any? %>
		<%= @ship.errors.messages[:name][0] %>
	<% end %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/ships/create.html.erb
<h1>Blogs#edit</h1>
<p>Find me in app/views/blogs/edit.html.erb</p>

app/views/ships/edit.html.erb
<h1>Edit ship</h1>
<%= render 'form' %>

app/views/ships/index.html.erb
<h1>Ships</h1>
<table>
	<tr>
		<th>Name</th>
		<th>Score</th>
	</tr>
	<% sum=0.0 %>
	<% @ships.each do |ship| %>
		<tr>
		<% equip_sum=(Math.sqrt(ship.score)*1.69) %>
		<% ship.equips.each do |equip| %>
			<% equip_sum+=equip.score*equip.rate %>
		<% end %>
		<% equip_sum=equip_sum.round(2) %>
		<% sum+=equip_sum %>
		<td><%= link_to ship.name,ship_path(ship.id) %></td>
		<td><%= equip_sum %></td>
		<td><%= link_to "Edit",edit_ship_path(ship.id) %></td>
		<td><%= link_to "Delete",ship_path(ship.id),method: :delete,data:{
			confirm:"よろしいですか？"} %></td>
		<td>
			<% ship.equips.each do |equip| %>
				<%= equip.name %>　
			<% end %>
		</td>
		</tr>
	<% end %>
</table>
<p>合計 ：<%= sum %><br>
司令Lvにより：<%= 120*(-0.61) %> => <%= sum=(sum+120*(-0.61)).round(1) %><br>
<% low=57.2 %>
<% high=70.4 %>
<% case sum %>
<% when 0..low then message="不足　@#{(high-sum).round(1)}" %>
<% when low...high then message="不確実　@#{(high-sum).round(1)}" %>
<% when high..200 then message="確実　+#{(sum-high).round(1)}" %>
<% else message="エラー" %>
<% end %>
判定：<%= message %>
<p> <%= link_to "create new",new_ship_path(:id) %> </p>


<p> <%= link_to "装備データ一覧",eq_data_path %> </p>

app/views/ships/new.html.erb
<h1>Add new ship</h1>
<%= render 'form' %>

app/views/ships/show.html.erb
<h1><%= @ship.name %></h1>
素の索敵値：<%= @ship.score %><p>
<% sum=0 %>
<table>
	<tr>
		<th>装備名</th>
		<th>評価値</th>
	</tr>
	<tr>
		<% sum=Math.sqrt(@ship.score)*1.69 %>
		<td>素の索敵値</td>
		<td><%= sum.round(2) %></td>
	</tr>
	<% @ship.equips.each do |equip| %>
		<tr>
			<% value=equip.score*equip.rate %>
			<% sum+=value %>
			<td><%= equip.name %></td>
			<td><%= value.round(2) %></td>
			<td>
			<%= link_to "Delete",ship_equip_path(equip.ship_id,equip.id),method: :delete,data:{confirm:"よろしいですか？"} %>
			</td>
		</tr>
	<% end %>
	<tr>
		<td>合計</td>
		<td><%= sum.round(2) %></td>
	</tr>
</table>
<br>

		
	偵察機
<%= form_for [@ship,@ship.equips.build] do |f|%>
	<%= f.collection_select :eq_datum_id, @teisatuki, :id, :view_name_and_scores %>
	<%= f.submit value="追加"%>
<% end %>
	電探
<%= form_for [@ship,@ship.equips.build] do |f|%>
	<%= f.collection_select :eq_datum_id, @dentan, :id, :view_name_and_scores %>
	<%= f.submit value="追加"%>
<% end %>
	その他
<%= form_for [@ship,@ship.equips.build] do |f|%>
	<%= f.collection_select :eq_datum_id, @other, :id, :view_name_and_scores %>
	<%= f.submit value="追加"%>
<% end %>